server:
  port: 7777

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java2tech
    username: root
    password: Password
    driverClassName: com.mysql.jdbc.Driver 
    #com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    show-sql : true
    hibernate:
      ddl-auto: update
      
  application:
    name: AUTH-SERVICE
  config:
    import: configserver:http://${CONFIG_SERVER_URL:localhost}:9296

jwt:
  secret: mySecretKey
  expireMs: 120000
  refrEshexpireMs: 120000
