server:
  port: 9296

#example
#spring.application.name=configserver
#spring.cloud.config.server.git.uri=https://github.com/<git-name>/config-server

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/alokebd/config-server
          clone-on-start: true
          skipSslValidation: true


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
